#!/bin/bash

[[ -z "$1" ]] && { echo "The version argument is needed"; exit 1;}

PKGNAME="xrootd-alicetokenacc"
VER=$1

PKG="${PKGNAME}-${VER}"
TARGZ="${PKG}.tar.gz"
DIR="${HOME}/tmp"
CURDIR="$(pwd)"

rm -rf ${DIR}/${PKG}

mkdir ${DIR}/${PKG}
rsync -rlptW --exclude '.git' --exclude "*.spec" --exclude "*.tar.gz" --exclude "create_*" --exclude ".gitlab*.yml" -ahuHAXW ${PWD}/ ${DIR}/${PKG}/

cd ${DIR}
tar -czf ${TARGZ} ./${PKG}
mv ${TARGZ} ${CURDIR}/

rm -rf ${DIR}/${TARGZ} ${DIR}/${PKG}
