#!/bin/bash

VER=$1
REL=$2

./create_targz ${VER}
rez=$?
[[ ${rez} == 1 ]] && { echo "Could not create targz"; exit 1;}

rpmdev-setuptree

mv -f xrootd-alicetokenacc-${VER}.tar.gz $HOME/rpmbuild/SOURCES/
cp -f xrootd-alicetokenacc.spec xrootd-alicetokenacc.spec_wip

sed -i "/Version:/c\Version: ${VER}" xrootd-alicetokenacc.spec_wip

[[ -n "${REL}" ]] && sed -i "/Release:/c\Release: ${REL}%{?dist}" xrootd-alicetokenacc.spec_wip
mv xrootd-alicetokenacc.spec_wip $HOME/rpmbuild/SPECS/xrootd-alicetokenacc.spec

rpmbuild -ba xrootd-alicetokenacc.spec

